name: Git Push Workflow Actions

on:
  push

jobs:
  defconfig-check:
    uses: varigit-dev/action-workflows/.github/workflows/defconfig-check.yml@master
    with:
      defconfig: >-
        arm64:imx8mm_var_dart_defconfig
        arm64:imx8mn_var_som_defconfig
        arm64:imx8mp_var_dart_defconfig
        arm64:imx8mq_var_dart_defconfig
        arm64:imx8qm_var_som_defconfig
        arm64:imx8qxp_var_som_defconfig
